### ISSUE TITLE
defaults aren't validated

### ISSUE THREAD

**Issue by dtkav** [p1c2u/openapi-spec-validator#32]
expected behavior:
a schema like this:
```
..
  parameters:
   - name: number
     schema:
       type: integer
       default: "bad_default"
```
should error because the default is the wrong type.

(behavior also recently added to https://github.com/Yelp/swagger_spec_validator)
